// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CallMCPTool(arg1, arg2, arg3) {
  return window['go']['desktop']['Bridge']['CallMCPTool'](arg1, arg2, arg3);
}

export function CancelAgentSession() {
  return window['go']['desktop']['Bridge']['CancelAgentSession']();
}

export function ClearChatSession(arg1) {
  return window['go']['desktop']['Bridge']['ClearChatSession'](arg1);
}

export function ExportSessionDiagnosticToFile(arg1, arg2) {
  return window['go']['desktop']['Bridge']['ExportSessionDiagnosticToFile'](arg1, arg2);
}

export function GetAllMCPServerStatuses() {
  return window['go']['desktop']['Bridge']['GetAllMCPServerStatuses']();
}

export function GetEvaluations() {
  return window['go']['desktop']['Bridge']['GetEvaluations']();
}

export function GetMCPServerStatus(arg1) {
  return window['go']['desktop']['Bridge']['GetMCPServerStatus'](arg1);
}

export function GetRequirements() {
  return window['go']['desktop']['Bridge']['GetRequirements']();
}

export function GetSessionDiagnostic(arg1) {
  return window['go']['desktop']['Bridge']['GetSessionDiagnostic'](arg1);
}

export function GetSettings() {
  return window['go']['desktop']['Bridge']['GetSettings']();
}

export function GetSubAgent(arg1) {
  return window['go']['desktop']['Bridge']['GetSubAgent'](arg1);
}

export function GetWorkspace() {
  return window['go']['desktop']['Bridge']['GetWorkspace']();
}

export function ListAllMCPTools() {
  return window['go']['desktop']['Bridge']['ListAllMCPTools']();
}

export function ListFiles(arg1) {
  return window['go']['desktop']['Bridge']['ListFiles'](arg1);
}

export function ListMCPTools(arg1) {
  return window['go']['desktop']['Bridge']['ListMCPTools'](arg1);
}

export function ListSessionDiagnostics(arg1) {
  return window['go']['desktop']['Bridge']['ListSessionDiagnostics'](arg1);
}

export function ListSubAgents() {
  return window['go']['desktop']['Bridge']['ListSubAgents']();
}

export function OpenFolderDialog() {
  return window['go']['desktop']['Bridge']['OpenFolderDialog']();
}

export function ReadFile(arg1) {
  return window['go']['desktop']['Bridge']['ReadFile'](arg1);
}

export function ReadSubAgentTranscript(arg1, arg2) {
  return window['go']['desktop']['Bridge']['ReadSubAgentTranscript'](arg1, arg2);
}

export function RunAgentSession(arg1) {
  return window['go']['desktop']['Bridge']['RunAgentSession'](arg1);
}

export function RunBuild(arg1, arg2) {
  return window['go']['desktop']['Bridge']['RunBuild'](arg1, arg2);
}

export function RunChatSession(arg1) {
  return window['go']['desktop']['Bridge']['RunChatSession'](arg1);
}

export function RunImplement(arg1, arg2) {
  return window['go']['desktop']['Bridge']['RunImplement'](arg1, arg2);
}

export function RunSpec(arg1, arg2) {
  return window['go']['desktop']['Bridge']['RunSpec'](arg1, arg2);
}

export function RunTask(arg1) {
  return window['go']['desktop']['Bridge']['RunTask'](arg1);
}

export function RunUIScan(arg1) {
  return window['go']['desktop']['Bridge']['RunUIScan'](arg1);
}

export function RunVerify(arg1, arg2) {
  return window['go']['desktop']['Bridge']['RunVerify'](arg1, arg2);
}

export function SaveFile(arg1, arg2) {
  return window['go']['desktop']['Bridge']['SaveFile'](arg1, arg2);
}

export function SaveSettings(arg1) {
  return window['go']['desktop']['Bridge']['SaveSettings'](arg1);
}

export function SetWorkspace(arg1) {
  return window['go']['desktop']['Bridge']['SetWorkspace'](arg1);
}

export function StopSubAgent(arg1, arg2) {
  return window['go']['desktop']['Bridge']['StopSubAgent'](arg1, arg2);
}

export function TestAllMCPServers() {
  return window['go']['desktop']['Bridge']['TestAllMCPServers']();
}

export function TestMCPServer(arg1) {
  return window['go']['desktop']['Bridge']['TestMCPServer'](arg1);
}
