// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {desktop} from '../models';

export function CallMCPTool(arg1:string,arg2:string,arg3:Record<string, any>):Promise<Record<string, any>>;

export function CancelAgentSession():Promise<void>;

export function GetAllMCPServerStatuses():Promise<Record<string, desktop.MCPServerStatus>>;

export function GetEvaluations():Promise<Record<string, any>>;

export function GetMCPServerStatus(arg1:string):Promise<desktop.MCPServerStatus>;

export function GetRequirements():Promise<Record<string, any>>;

export function GetSettings():Promise<desktop.Settings>;

export function GetWorkspace():Promise<Record<string, any>>;

export function ListAllMCPTools():Promise<Record<string, any>>;

export function ListFiles(arg1:string):Promise<Record<string, any>>;

export function ListMCPTools(arg1:string):Promise<Array<Record<string, any>>>;

export function OpenFolderDialog():Promise<string>;

export function ReadFile(arg1:string):Promise<Record<string, any>>;

export function RunAgentSession(arg1:string,arg2:string,arg3:string):Promise<desktop.RunResult>;

export function RunTask(arg1:string,arg2:string,arg3:string):Promise<desktop.RunResult>;

export function RunTaskWithProgress(arg1:string,arg2:string,arg3:string):Promise<desktop.RunResult>;

export function SaveFile(arg1:string,arg2:string):Promise<void>;

export function SaveSettings(arg1:desktop.Settings):Promise<void>;

export function SetWorkspace(arg1:string):Promise<void>;

export function TestAllMCPServers():Promise<Record<string, desktop.MCPServerStatus>>;

export function TestMCPServer(arg1:string):Promise<desktop.MCPServerStatus>;
