// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {desktop} from '../models';
import {audit} from '../models';

export function CallMCPTool(arg1:string,arg2:string,arg3:Record<string, any>):Promise<Record<string, any>>;

export function CancelAgentSession():Promise<void>;

export function ExportSessionDiagnosticToFile(arg1:string,arg2:string):Promise<string>;

export function GetAllMCPServerStatuses():Promise<Record<string, desktop.MCPServerStatus>>;

export function GetEvaluations():Promise<Record<string, any>>;

export function GetMCPServerStatus(arg1:string):Promise<desktop.MCPServerStatus>;

export function GetRequirements():Promise<Record<string, any>>;

export function GetSessionDiagnostic(arg1:string):Promise<audit.DiagnosticDTO>;

export function GetSettings():Promise<desktop.Settings>;

export function GetSubAgent(arg1:string):Promise<desktop.SubAgentSnapshot>;

export function GetWorkspace():Promise<Record<string, any>>;

export function ListAllMCPTools():Promise<Record<string, any>>;

export function ListFiles(arg1:string):Promise<Record<string, any>>;

export function ListMCPTools(arg1:string):Promise<Array<Record<string, any>>>;

export function ListSessionDiagnostics(arg1:number):Promise<Array<audit.SessionIndex>>;

export function ListSubAgents():Promise<Array<desktop.SubAgentSnapshot>>;

export function OpenFolderDialog():Promise<string>;

export function ReadFile(arg1:string):Promise<Record<string, any>>;

export function ReadSubAgentTranscript(arg1:string,arg2:number):Promise<string>;

export function RunAgentSession(arg1:string):Promise<desktop.RunResult>;

export function RunBuild(arg1:string,arg2:string):Promise<desktop.RunResult>;

export function RunImplement(arg1:string,arg2:string):Promise<desktop.RunResult>;

export function RunSpec(arg1:string,arg2:string):Promise<desktop.RunResult>;

export function RunTask(arg1:string):Promise<desktop.RunResult>;

export function RunUIScan(arg1:string):Promise<desktop.RunResult>;

export function RunVerify(arg1:string,arg2:string):Promise<desktop.RunResult>;

export function SaveFile(arg1:string,arg2:string):Promise<void>;

export function SaveSettings(arg1:desktop.Settings):Promise<void>;

export function SetWorkspace(arg1:string):Promise<void>;

export function StopSubAgent(arg1:string,arg2:string):Promise<string>;

export function TestAllMCPServers():Promise<Record<string, desktop.MCPServerStatus>>;

export function TestMCPServer(arg1:string):Promise<desktop.MCPServerStatus>;
