// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CallMCPTool(arg1, arg2, arg3) {
  return window['go']['desktop']['Bridge']['CallMCPTool'](arg1, arg2, arg3);
}

export function CancelAgentSession() {
  return window['go']['desktop']['Bridge']['CancelAgentSession']();
}

export function GetAllMCPServerStatuses() {
  return window['go']['desktop']['Bridge']['GetAllMCPServerStatuses']();
}

export function GetEvaluations() {
  return window['go']['desktop']['Bridge']['GetEvaluations']();
}

export function GetMCPServerStatus(arg1) {
  return window['go']['desktop']['Bridge']['GetMCPServerStatus'](arg1);
}

export function GetRequirements() {
  return window['go']['desktop']['Bridge']['GetRequirements']();
}

export function GetSettings() {
  return window['go']['desktop']['Bridge']['GetSettings']();
}

export function GetWorkspace() {
  return window['go']['desktop']['Bridge']['GetWorkspace']();
}

export function ListAllMCPTools() {
  return window['go']['desktop']['Bridge']['ListAllMCPTools']();
}

export function ListFiles(arg1) {
  return window['go']['desktop']['Bridge']['ListFiles'](arg1);
}

export function ListMCPTools(arg1) {
  return window['go']['desktop']['Bridge']['ListMCPTools'](arg1);
}

export function OpenFolderDialog() {
  return window['go']['desktop']['Bridge']['OpenFolderDialog']();
}

export function ReadFile(arg1) {
  return window['go']['desktop']['Bridge']['ReadFile'](arg1);
}

export function RunAgentSession(arg1, arg2, arg3) {
  return window['go']['desktop']['Bridge']['RunAgentSession'](arg1, arg2, arg3);
}

export function RunTask(arg1, arg2, arg3) {
  return window['go']['desktop']['Bridge']['RunTask'](arg1, arg2, arg3);
}

export function RunTaskWithProgress(arg1, arg2, arg3) {
  return window['go']['desktop']['Bridge']['RunTaskWithProgress'](arg1, arg2, arg3);
}

export function SaveFile(arg1, arg2) {
  return window['go']['desktop']['Bridge']['SaveFile'](arg1, arg2);
}

export function SaveSettings(arg1) {
  return window['go']['desktop']['Bridge']['SaveSettings'](arg1);
}

export function SetWorkspace(arg1) {
  return window['go']['desktop']['Bridge']['SetWorkspace'](arg1);
}

export function TestAllMCPServers() {
  return window['go']['desktop']['Bridge']['TestAllMCPServers']();
}

export function TestMCPServer(arg1) {
  return window['go']['desktop']['Bridge']['TestMCPServer'](arg1);
}
