ALTER TABLE runs ADD COLUMN IF NOT EXISTS input_messages JSONB;
ALTER TABLE runs ADD COLUMN IF NOT EXISTS pipeline_stages JSONB;
ALTER TABLE chat_sessions ADD COLUMN IF NOT EXISTS messages JSONB;
ALTER TABLE plans ADD COLUMN IF NOT EXISTS resolutions TEXT;
